---
name: Run Linux commands
on:
  workflow_dispatch: null
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Execute linux commands
        run: echo "HELLO ALL"
  job2:
    runs-on: ubuntu-22.04
    steps:
      - name: Execute set of linux commands
        run: |
          hostname -s
          echo "THANK YOU ALL"
